version: "3"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  db_seed:
    build: ./server/db-seed
    depends_on:
      - db

  db_admin:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
    expose:
      - ${DB_ADMIN_PORT}
    ports:
      - ${DB_ADMIN_PORT}:8081
    depends_on:
      - db

  server:
    build: ./server
    command: npm run dev
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./server/src:/usr/app/ebay-alert-api/src
    depends_on:
      - db
    environment:
      - API_PORT=${API_PORT}
      - DB_URL=${DB_URL}
      - EBAY_APP_ID=${EBAY_APP_ID}
      - EBAY_SEARCH_API_URL=${EBAY_SEARCH_API_URL}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD}

  client:
    build: ./client
    command: npm run start
    expose:
      - ${WEB_PORT}
      - 35729
    ports:
      - ${WEB_PORT}:3000
      - 35729:35729
    volumes:
      - /usr/app/ebay-alert-web/node_modules
      - ./client/src:/usr/app/ebay-alert-web/src
    depends_on:
      - server
    environment:
      - REACT_APP_API_HOST=${REACT_APP_API_HOST}
