version: "3"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017

  db_seed:
    build: ./server/db-seed
    depends_on:
      - db

  server-test:
    build: ./server
    command: npm run test
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./server/src:/usr/app/ebay-alert-api/src
      - ./server/tests:/usr/app/ebay-alert-api/tests
      - ./server/package.json:/usr/app/ebay-alert-api/package.json
    depends_on:
      - db_seed
    environment:
      - API_PORT=${API_PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=test

  client-test:
    build: ./client
    command: npm run test
    expose:
      - ${WEB_PORT}
      - 35729
    ports:
      - ${WEB_PORT}:3000
      - 35729:35729
    volumes:
      - /usr/app/ebay-alert-web/node_modules
      - ./client/src:/usr/app/ebay-alert-web/src
      - ./client/__tests__:/usr/app/ebay-alert-web/__tests__
      - ./client/__mocks__:/usr/app/ebay-alert-web/__mocks__
      - ./client/package.json:/usr/app/ebay-alert-web/package.json
    depends_on:
      - server-test
    environment:
      - NODE_ENV=test
      - REACT_APP_API_HOST=${REACT_APP_API_HOST}
      - REACT_APP_HOST=${REACT_APP_HOST}
      - REACT_APP_PORT=${WEB_PORT}

