version: "3"

services:
  client:
    build: ./client
    command: npm run test
    volumes:
      - /usr/app/ebay-alert-web/node_modules
      - ./client/src:/usr/app/ebay-alert-web/src
      - ./client/__tests__:/usr/app/ebay-alert-web/__tests__
    environment:
      - REACT_APP_API_HOST=${REACT_APP_API_HOST}




      
