version: "3"

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017

  db_seed:
    build: ./db-seed
    depends_on:
      - db

  ebay-alert-api-test:
    build: ./
    command: npm run test
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./src:/usr/app/ebay-alert-api/src
      - ./tests:/usr/app/ebay-alert-api/tests
      - ./package.json:/usr/app/ebay-alert-api/package.json
    depends_on:
      - db_seed
    environment:
      - API_PORT=${API_PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=test

